### ISSUE TITLE
Add Google API Authorization

### ISSUE THREAD

**Issue by sfaria27** [tiki/google_provider#6]
Should ~be able to submit an email address using the app~ open~ing~ Google OAuth form. 

Acceptance Criteria:
1. Upon completion, a log-in callback should be triggered. 
2. Upon failure, a failure callback should be triggered.

**Comment by mike-audi** [comment]
set the widget state model with the email address

**Comment by sfaria27** [comment]
@ricardobrg fix android dynamic links and fix expiration dates
