### ISSUE TITLE
Define standardized information for "They Know info" cards

### ISSUE THREAD

**Issue by sfaria27** [tiki/google_provider#9]
Write API to return "They know information" for each connected service.

Acceptance criteria:
1. Current card carousel should work
![image](https://user-images.githubusercontent.com/81697281/153022055-5886876f-ce01-4750-ba31-ed2039685797.png)
![image](https://user-images.githubusercontent.com/81697281/153022110-a3b1ae1a-a9a6-4a67-bdb1-4c1852ea1fde.png)
![image](https://user-images.githubusercontent.com/81697281/153022157-ca80219a-d5b5-4915-8286-dd48d604d153.png)
![image](https://user-images.githubusercontent.com/81697281/153022192-81a4f4b5-70c8-4a55-bfcc-226fa033c24c.png)
![image](https://user-images.githubusercontent.com/81697281/153022223-25a5fb21-7fb0-45f8-a437-891c19f36236.png)
![image](https://user-images.githubusercontent.com/81697281/153022242-16bef109-7f0c-42c9-825d-46814aeb631f.png)

**Comment by mike-audi** [comment]
use JSON model as structure for Dart model
